### ISSUE TITLE
License

### ISSUE THREAD

**Issue by arturo182** [pinout-xyz/pico2.pinout.xyz#2]
This repo together with pico and picow are all missing a `LICENSE`. I would love to fork this and customize it for the Stamp, but of course only if there's a license that allows it :)

**Comment by Gadgetoid** [comment]
For you, sir, and ignoring the company logos and such contained herein that are their own sticky mess, you can have an irrevocable, perpetual license to make as many Stamp (or other product) pinouts as you'd like 😆 

But yes, otherwise MIT which is basically the same thing but with more legal words.

**Comment by arturo182** [comment]
Ah, the APL - Arturo Public License 😁
